name: TechTrends - Package with Docker
on:
  push:
    branches:
      - 'main'
jobs:
  docker-build-techtrends:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #checkout current workspace
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            diogosilverio/techtrends:latest
            diogosilverio/techtrends:${GITHUB_SHA::12}
